In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# Part- 1 #
import pandas as pd
df=pd.read_csv("/content/online_shopping_uncleaned_20000_rows.csv")
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1,1.0,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,NaN,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,NaN,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1,3.0,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,NaN,4.0,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,NaN,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3,NaN,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,NaN,2.0,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7,NaN,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,NaN,1,2.0,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
df.head(10)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1,1.0,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,NaN,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,NaN,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1,3.0,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,NaN,4.0,returned,chennai,15,NaN,NaN,Platinum
5,5,17850.0,M,Chicago,12.0,16701.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,FAILED,2,2.0,NaN,Delhi,NaN,Low,2,Gold
6,6,17850.0,M,Chicago,12.0,16702.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,NaN,5.0,Not Returned,chennai,unknown,high,unknown,NaN
7,7,17850.0,M,Chicago,12.0,16703.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Pending,7,4.0,returned,Mumbai,10,Low,2,NaN
8,8,17850.0,M,Chicago,12.0,16704.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,4.0,returned,Delhi,5,High,0,Platinum
9,9,17850.0,M,Chicago,12.0,16710.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Paid,10days,NaN,Returned,Mumbai,5,unknown,NaN,Gold

In [ ]:
df.tail(10)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
19990,19990,14309.0,F,New Jersey,49.0,30594.0,2019-06-17,GGOEGOLC014299,Google Metallic Notebook Set,Office,...,30.0,Pending,1,1.0,NONE,NaN,unknown,NaN,NaN,NaN
19991,19991,14309.0,F,New Jersey,49.0,30595.0,2019-06-17,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,Paid,NaN,5.0,Not Returned,Chennai,15,NaN,2,Silver
19992,19992,15291.0,M,California,32.0,31203.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,paid,3,3.0,NaN,Unknown,5,unknown,unknown,NaN
19993,19993,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEAFKQ020599,Android Sticker Sheet Ultra Removable,Office,...,30.0,Pending,3,NaN,NaN,NaN,5,Low,3,NaN
19994,19994,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,Paid,7,NaN,Not Returned,chennai,5,Low,3,gold
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,NaN,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3,NaN,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,NaN,2.0,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7,NaN,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,NaN,1,2.0,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
df.shape

(20000, 30)

In [ ]:
# Part-2 #
df.columns

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct',
       'Payment_Status', 'Delivery_Days', 'Customer_Rating', 'Return_Status',
       'Customer_City', 'Discount_Percent', 'Order_Priority', 'Support_Calls',
       'Membership'],
      dtype='object')

In [ ]:
df.dtypes

Unnamed: 0               int64
CustomerID             float64
Gender                  object
Location                object
Tenure_Months          float64
Transaction_ID         float64
Transaction_Date        object
Product_SKU             object
Product_Description     object
Product_Category        object
Quantity               float64
Avg_Price              float64
Delivery_Charges       float64
Coupon_Status           object
GST                    float64
Date                    object
Offline_Spend          float64
Online_Spend           float64
Month                    int64
Coupon_Code             object
Discount_pct           float64
Payment_Status          object
Delivery_Days           object
Customer_Rating        float64
Return_Status           object
Customer_City           object
Discount_Percent        object
Order_Priority          object
Support_Calls           object
Membership              object
dtype: object

In [ ]:
df.describe()

,Unnamed: 0,CustomerID,Tenure_Months,Transaction_ID,Quantity,Avg_Price,Delivery_Charges,GST,Offline_Spend,Online_Spend,Month,Discount_pct,Customer_Rating
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,19917.000000,15012.000000
mean,9999.500000,15384.448800,26.419000,31757.398950,4.403900,56.511256,11.07499,0.134707,2998.910000,1960.758028,6.345150,22.944219,3.175793
std,5773.647028,1790.469818,13.522188,10442.150226,21.192688,63.316612,20.61016,0.044485,1116.007655,849.627815,3.993798,7.820770,1.338989
min,0.000000,12347.000000,2.000000,16679.000000,1.000000,0.390000,0.00000,0.050000,500.000000,320.250000,1.000000,10.000000,1.000000
25%,4999.750000,13819.000000,15.000000,22285.000000,1.000000,6.180000,6.00000,0.100000,2000.000000,1296.810000,3.000000,20.000000,2.000000
50%,9999.500000,15311.000000,27.000000,34498.500000,1.000000,19.190000,6.50000,0.100000,3000.000000,1918.530000,8.000000,20.000000,4.000000
75%,14999.250000,17114.000000,38.000000,36871.000000,2.000000,119.000000,6.50000,0.180000,4000.000000,2546.580000,8.000000,30.000000,4.000000
max,19999.000000,18260.000000,50.000000,48497.000000,825.000000,355.740000,521.36000,0.180000,5000.000000,4055.300000,12.000000,30.000000,5.000000

In [ ]:
df.nunique()

Unnamed: 0             20000
CustomerID               889
Gender                     2
Location                   5
Tenure_Months             49
Transaction_ID         10153
Transaction_Date         154
Product_SKU             1012
Product_Description      385
Product_Category          20
Quantity                 111
Avg_Price                457
Delivery_Charges         185
Coupon_Status              3
GST                        4
Date                     154
Offline_Spend             11
Online_Spend             154
Month                      5
Coupon_Code                5
Discount_pct               3
Payment_Status             5
Delivery_Days              7
Customer_Rating            5
Return_Status              4
Customer_City              5
Discount_Percent           6
Order_Priority             5
Support_Calls              6
Membership                 4
dtype: int64

In [ ]:
df.isnull().sum()

Unnamed: 0                0
CustomerID                0
Gender                    0
Location                  0
Tenure_Months             0
Transaction_ID            0
Transaction_Date          0
Product_SKU               0
Product_Description       0
Product_Category          0
Quantity                  0
Avg_Price                 0
Delivery_Charges          0
Coupon_Status             0
GST                       0
Date                      0
Offline_Spend             0
Online_Spend              0
Month                     0
Coupon_Code            3356
Discount_pct             83
Payment_Status         3252
Delivery_Days          2395
Customer_Rating        4988
Return_Status          4076
Customer_City          3421
Discount_Percent       2849
Order_Priority         3356
Support_Calls          2856
Membership             6717
dtype: int64

In [ ]:
# Part - 3 #
df.isnull().sum()

Unnamed: 0                0
CustomerID                0
Gender                    0
Location                  0
Tenure_Months             0
Transaction_ID            0
Transaction_Date          0
Product_SKU               0
Product_Description       0
Product_Category          0
Quantity                  0
Avg_Price                 0
Delivery_Charges          0
Coupon_Status             0
GST                       0
Date                      0
Offline_Spend             0
Online_Spend              0
Month                     0
Coupon_Code            3356
Discount_pct             83
Payment_Status         3252
Delivery_Days          2395
Customer_Rating        4988
Return_Status          4076
Customer_City          3421
Discount_Percent       2849
Order_Priority         3356
Support_Calls          2856
Membership             6717
dtype: int64

In [ ]:
df['Customer_Rating'].fillna(df['Customer_Rating'].mean(), inplace=True)
df

/tmp/ipykernel_273/905697380.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_Rating'].fillna(df['Customer_Rating'].mean(), inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1.000000,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3.0,3.175793,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3.175793,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3.000000,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,3.0,4.000000,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3.175793,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3.0,3.175793,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2.000000,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7.0,3.175793,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1.0,2.000000,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
df['Payment_Status'].fillna( 'unknown',inplace=True)
df

/tmp/ipykernel_273/3494347214.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Payment_Status'].fillna( 'unknown',inplace=True)

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1.0,1.000000,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,unknown,3.0,3.175793,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5.0,3.175793,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1.0,3.000000,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,3.0,4.000000,returned,chennai,15,NaN,NaN,Platinum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1.0,3.175793,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3.0,3.175793,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,3.0,2.000000,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7.0,3.175793,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,unknown,1.0,2.000000,Not Returned,Chennai,NaN,Low,4calls,gold

In [ ]:
df['Delivery_Days'] = pd.to_numeric(df['Delivery_Days'], errors='coerce')
df['Delivery_Days'].fillna(df['Delivery_Days'].median(), inplace=True)

/tmp/ipykernel_273/1594981114.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Delivery_Days'].fillna(df['Delivery_Days'].median(), inplace=True)

In [ ]:
df['Coupon_Code'].fillna('No Coupon',inplace=True)

/tmp/ipykernel_273/1347806141.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Coupon_Code'].fillna('No Coupon',inplace=True)

In [ ]:
df.isnull().sum()

Unnamed: 0                0
CustomerID                0
Gender                    0
Location                  0
Tenure_Months             0
Transaction_ID            0
Transaction_Date          0
Product_SKU               0
Product_Description       0
Product_Category          0
Quantity                  0
Avg_Price                 0
Delivery_Charges          0
Coupon_Status             0
GST                       0
Date                      0
Offline_Spend             0
Online_Spend              0
Month                     0
Coupon_Code               0
Discount_pct             83
Payment_Status            0
Delivery_Days             0
Customer_Rating           0
Return_Status          4076
Customer_City          3421
Discount_Percent       2849
Order_Priority         3356
Support_Calls          2856
Membership             6717
dtype: int64